#
name:         XML-RSS-FOXSports
version:      0.02
version_from: lib/XML/RSS/FOXSports.pm
installdirs:  site
requires:
    XML::RSS::Parser               2.15

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12